config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'frontend/home#index'
  get 'ping', to: 'home#ping'

  post 'subscriptions', to: 'subscriptions#create'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest('admin')) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest('admin'))
  end if Rails.env.production?

  mount Sidekiq::Web, at: "/sidekiq"

  get '/sitemap.xml' => redirect('https://et-allcollate-production.s3.amazonaws.com/sitemaps/sitemap.xml', status: 301)

  scope module: 'frontend' do
    resources :hotels, only: [:show], path: 'hotel' do
      get :compare
    end

    resource :search, only: :show do
      get :suggestions
    end

    resources :comparisons, only: [:index]
  end

  namespace 'api' do
    resources :search, only: [:index] do
      collection do
        get :locations
        get :brands
      end
    end

    resources :comparisons, only: [:index]
  end

  post '/api/login', to: 'api/base_controller#authenticate_user'
  get '/directory/companies/:prefix' => 'frontend/directory/hotels#show', constraints: {
    prefix: /([a-z]|more)(\-\d*)?/
  }, as: :hotel_directory
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  include Sluggable

  sluggable_from :name

  update_index('hotels') { self if active? } if Rails.env.production?

  belongs_to :brand, optional: true

  after_save :update_counter_cache
  after_destroy :update_counter_cache

  has_many :rates
  has_many :photos

  enum hotel_state: { active: 'active', draft: 'draft', pending: 'pending' }

  def self.latest_rates_between(start_rate, end_rate)
    joins(:rates).where('rates.actual_on >= ?', Date.today - 1.months)
                 .group('hotels.id', 'photos.id', 'rates.id')
                 .having('AVG(rates.daily_rate) BETWEEN ? and ?', start_rate, end_rate)
  end

  def self.latest_rates_more_than(rate)
    joins(:rates).where('rates.actual_on >= ?', Date.today - 1.months)
                 .group('hotels.id', 'photos.id', 'rates.id')
                 .having('AVG(rates.daily_rate) >= ?', rate)
  end

  def self.latest_rates_less_than(rate)
    joins(:rates).where('rates.actual_on >= ?', Date.today - 1.months)
                 .group('hotels.id', 'photos.id', 'rates.id')
                 .having('AVG(rates.daily_rate) <= ?', rate)
  end

  def self.ransackable_scopes(_auth_object = nil)
    %i[latest_rates_between latest_rates_more_than latest_rates_less_than]
  end

  def rate
    12
  end

  private

  def update_counter_cache
    brand.update_hotels_count
  end
end

app/controllers/frontend/directory/hotels_controller.rb
class Frontend::Directory::HotelsController < Frontend::BaseController
  # before_action :check_prefix

  PER_PAGE = 75

  def show
    # Moved permanently for the legacy URLs
    if params[:page]
      path = "#{params[:prefix]}-#{params[:page]}"
      redirect_to hotel_directory_path(path), status: :moved_permanently and return
    end

    @prefix, @page = params[:prefix].split('-')
    @hotels = if @prefix == 'more'
                Hotel.active.ransack(name_not_start_all: ('a'..'z'))
              else
                Hotel.active.ransack(name_start: @prefix)
              end.result.order(:name).page(@page).per_page(PER_PAGE)
  end
end

app/controllers/frontend/hotels_controller.rb
class Frontend::HotelsController < Frontend::BaseController
  COMPARE_PER_PAGE = 3

  def show
    @hotel = Hotel.active.includes(:photos, :rates).friendly.find(params[:id])
  end

  def compare
    hotel = Hotel.active.find_by(slug: params[:hotel_id])
    search = Services::EsSearch::Hotel.new(compare_params_for(hotel))

    ids = search.do.map(&:id)
    ids.unshift(hotel.id)

    hotels = Hotel.active.where(id: ids).last(100)

    @hotels_json = HotelCompareSerializer.new(hotels, is_collection: true).serializable_hash[:data]
                                         .map { |item| item[:attributes] }
  end

  private

  def compare_params_for(hotel)
    params = {}

    params[:locations] = [{ 'city' => hotel.city, 'country' => hotel.country }] if hotel.city && hotel.country
    params[:yearRenovated] = [hotel.year_renovated - 10, hotel.year_renovated + 10] if hotel.year_renovated
    params[:yearOpened] = [hotel.year_opened - 10, hotel.year_opened + 10] if hotel.year_opened
    params[:starRating] = [hotel.star_rating - 1, hotel.star_rating + 1] if hotel.star_rating

    rate = hotel.rates.order(actual_on: :desc).first&.daily_rate
    params[:rates] = [rate * 0.7, rate * 1.3] if rate

    params[:perPage] = COMPARE_PER_PAGE

    params
  end
end

app/views/frontend/directory/hotels/show.slim
= content_for :canonical_tag do
  link href="#{hotel_directory_url(prefix: [@prefix, @page].compact.join('-'))}" rel='canonical'

= content_for :stylesheet_link_tag do
  = stylesheet_link_tag 'directory-show', media: 'all'

.main
  .page-content
    .container
      h1.directory__title Hotel Directory

      .directory__prefix
        span.directory__browse Browse:
        nav.directory__navigation
          ul.pagination
            - ('A'..'Z').each do |item|
              li.page-item class=('directory__navigation--active' if @prefix == item.downcase)
                = link_to item, hotel_directory_path(prefix: item.downcase), class: 'page-link'
            li.page-item class=('active' if @prefix == 'more')
                = link_to '#', hotel_directory_path(prefix: 'more'), class: 'page-link'

      .directory__hotels.row
        - @hotels.each_slice(25) do |hotels|
          .col-md-4
            ul.directory__hotels_list
              - hotels.each do |hotel|
                li
                  = link_to hotel.name, hotel_path(hotel)

      .directory__browse_pages_container
        span Browse pages:
        ul.directory__browse_pages_whitespace
          - 1.upto(@hotels.total_pages).each do |page|
            li.directory__browse_pages_item
              - prefix = page == 1 ? @prefix : [@prefix, page].join('-')
              = link_to page, hotel_directory_path(prefix: "#{prefix}"),
                class: ('directory__browse_pages_item--active' if @page.to_i == page || (@page.nil? && page == 1 ))