config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'frontend/home#index'
  get 'ping', to: 'home#ping'

  post 'subscriptions', to: 'subscriptions#create'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest('admin')) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest('admin'))
  end if Rails.env.production?

  mount Sidekiq::Web, at: "/sidekiq"

  get '/sitemap.xml' => redirect('https://et-allcollate-production.s3.amazonaws.com/sitemaps/sitemap.xml', status: 301)

  scope module: 'frontend' do
    resources :hotels, only: [:show], path: 'hotel' do
      get :compare
    end

    resource :search, only: :show do
      get :suggestions
    end

    resources :comparisons, only: [:index]
  end

  namespace 'api' do
    resources :search, only: [:index] do
      collection do
        get :locations
        get :brands
      end
    end

    resources :comparisons, only: [:index]
  end

  post '/api/login', to: 'api/base_controller#authenticate_user'
  get '/directory/companies/:prefix' => 'frontend/directory/hotels#show', constraints: {
    prefix: /([a-z]|more)(\-\d*)?/
  }, as: :hotel_directory
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Allcollate - Compare hotels, price, rooms</title>
    <meta content='Allcollate is an analytics platform providing comparing and analyzing for hotels. We collect and organize data from thousands of sources to provide up-to-date information, prices, rooms across the whole world.' name='description' />

    <meta content='Allcollate - Compare hotels, price, rooms' property='og:title'>
    <meta content='Allcollate is an analytics platform providing comparing and analyzing for hotels. We collect and organize data from thousands of sources to provide up-to-date information, prices, rooms across the whole world.' property='og:description'>

    <link href='http://www.allcollate.com' rel='canonical'>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= yield(:stylesheet_link_tag) %>


    <%- if Rails.env.production? %>
      <script async src='https://www.googletagmanager.com/gtag/js?id=UA-167845499-1'></script>

      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-167845499-1');
      </script>

      <!-- Google Tag Manager -->
      <script>
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-T9G8H4C');
      </script>
      <!-- End Google Tag Manager -->

      <script src="https://www.googleoptimize.com/optimize.js?id=OPT-KSNSK8X"></script>
    <% end %>

    <%= javascript_pack_tag 'application' %>
    <%#= stylesheet_pack_tag 'application' %>

    <%= yield(:javascript_pack_tag) %>
    <%= yield(:stylesheet_pack_tag) %>

    <meta name="agd-partner-manual-verification" />
  </head>

  <body>
    <%- if Rails.env.production? %>
      <!-- Google Tag Manager (noscript) -->
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T9G8H4C"
      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
      <!-- End Google Tag Manager (noscript) -->
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/frontend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Allcollate - Compare hotels, price, rooms</title>
    <meta content='Allcollate is an analytics platform providing comparing and analyzing for hotels. We collect and organize data from thousands of sources to provide up-to-date information, prices, rooms across the whole world.' name='description' />

    <meta content='Allcollate - Compare hotels, price, rooms' property='og:title'>
    <meta content='Allcollate is an analytics platform providing comparing and analyzing for hotels. We collect and organize data from thousands of sources to provide up-to-date information, prices, rooms across the whole world.' property='og:description'>

    <link href='http://www.allcollate.com' rel='canonical'>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'frontend', media: 'all' %>
    <%= yield(:stylesheet_link_tag) %>


    <%- if Rails.env.production? %>
      <script async src='https://www.googletagmanager.com/gtag/js?id=UA-167845499-1'></script>

      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-167845499-1');
      </script>

      <!-- Google Tag Manager -->
      <script>
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-T9G8H4C');
      </script>
      <!-- End Google Tag Manager -->

      <script src="https://www.googleoptimize.com/optimize.js?id=OPT-KSNSK8X"></script>

      <!-- Feedback form -->
      <script>
        window.formOptions={'surveyID':8681064,'domain':'https://www.questionpro.com/a/','allowMultipleTakes':false};
      </script>
      <script src="https://www.questionpro.com/javascript/conversationalsurvey/form.js" async></script>
    <% end %>

    <%= javascript_pack_tag 'application' %>

    <%= yield(:javascript_pack_tag) %>
    <%= yield(:stylesheet_pack_tag) %>

    <meta name="agd-partner-manual-verification" />
  </head>

  <body>
    <%- if Rails.env.production? %>
      <!-- Google Tag Manager (noscript) -->
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T9G8H4C"
      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
      <!-- End Google Tag Manager (noscript) -->
    <% end %>

  <div class="page">
    <div class="page-main">
      <div class="search-header">
        <div class="container header-container">

          <%- if flash.notice %>
            <%= react_component('FlashMessage/index', { message: 'Everything is almost done! Just the last step, please, confirm your email.' }, prerender: false) %>
          <% end %>

          <div class="d-flex">
            <div class="main-header-py4">
              <div class="d-flex main-header">
                <div class="order-lg-2 header-brand-title">
                  <a class="navbar-brand allcollate-title-link" href='/'>
                    <span class="allcollate-title"> Allcollate </span>
                  </a>
                  <span class="allcollate-title allcollate-title-beta"> beta </span>

                  <%= react_component('AutoSuggestionSearch/SuggestionForm', { query: params[:q] }, prerender: false, class: 'suggestion-form__container') %>
                  <div class="header__login-block col-md-5">
                    <%- if current_user %>
                      <%= link_to 'Sign Out', logout_path, class: 'header__login-link' %>
                    <% else %>
                      <%= link_to 'Log In', authentication_path, method: :post, class: 'header__login-link' %>
                      <%= link_to 'Sign Up', authentication_path(screen_hint: :signup), method: :post, class: 'header__signup-link' %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div >

      <%= yield %>
    </div>
    <div class="footer">
      <div class="container">
        <div class="row align-items-center flex-row-reverse">
          <div class="col col-auto ml-auto">
            <div class="row row align-items-center">
              <%= link_to 'Hotel directory', hotel_directory_path(prefix: 'a') %>
            </div>
          </div>
          <div class="col col-12 col-lg-auto mt-3 mt-lg-0 text-center">
            &copy;
            <%= Date.current.year %>
            <%= link_to ' allcollate.com', root_path %>
            All rights reserved.
          </div>
        </div>
      </div>
    </div>
  </div>

  </body>
</html>